# Generated by Django 4.1.3 on 2022-11-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='data',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Значение глюкометра'),
        ),
    ]
